* rake_bundle_gem

** description

Create gem using bundler with a nested module.

** install

Download from [[https://github.com/tomiacannondale/rake_bundle_gem][rake_bundle_gem homepage]]

or

Clone git repository from [[https://tomiacannondale@github.com/tomiacannondale/rake_bundle_gem.git][rake bundle gem repository]]


Copy Rakefile to your code directory.

** usage

: rake bundle_gem gem=your gem name

** example

Excute the following comand.

: rake bundle_gem gem=foo-baa

- Excute bundle gem foo-bar.
- Move lib/foo-bar directory to lib/foo/bar(use git mv).
- Move lib/foo-bar.rb to lib/foo/bar.rb(use git mv).
- Change require path from foo-bar to foo/bar.
- Change shebang from "-*- encoding: utf-8 -*-" to "-*- coding: utf-8 -*-" (to control on emacs).

** license

Copyright (c) 2011 tomi

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
